### ISSUE TITLE
Can't create project on Win7

### ISSUE THREAD

**Issue by enesj** [sveri/closp#1] opened 2015-02-20 09:14 UTC
When I try to create new project with "lein new closp _projectname_ -n foo.bar", I am receiving this message:
Could not load template, failed with: java.lang.RuntimeException: No such var: t-cli/parse-opts, compiling:(leiningen/new/closp.clj:102:52)

Thanks
Enes

**Comment by sveri** [comment] 2015-02-20 11:44
Hm, that's a weird one. I did exactly this like 40 times in the last two weeks, on W7 myself.
Maybe it's an environmental issue. I try to figure out what is going on here.

**Comment by sveri** [comment] 2015-02-20 12:35
I just cleaned all my caches and emptied my users profiles.clj. Then I executed this: `lein new closp projectname -n foo.bar`
It works. I do this from a normal windows cmd line, with User rights (no administrator cmd).
I am using J8.

Could you please give some more details about your environment (Java version, leiningen version, etc).

**Comment by enesj** [comment] 2015-02-20 12:55
That is output of lein version:

Leiningen 2.5.0 on Java 1.7.0_11 Java HotSpot(TM) 64-Bit Server VM

**Comment by sveri** [comment] 2015-02-20 21:39
Hm, it works for me with JDK 1.7.0.51 too. Do you have the jdk installed? Or only the JRE? Do you have JAVA_HOME set? And where to?

**Comment by sveri** [comment] 2015-02-20 22:23
Maybe you could also try to clean your .m2 folder in %userhome%?

**Comment by enesj** [comment] 2015-02-22 13:08
Hello, I've just tried on another PC, and everything works as described in Readme. 
I will try to see what is the problem with first PC.

**Comment by enesj** [comment] 2015-02-23 11:23
I did clear .m2 and created java-home system var (C:\Program Files\Java\jdk1.7.0_11) and still have same error on first PC.

**Comment by sveri** [comment] 2015-02-23 14:31
You need to name the system var: JAVA_HOME exactly like this, however, I don't think it will solve the problem.
Could your post your profiles.clj please? You can find it in %userhome$.lein.

**Comment by enesj** [comment] 2015-02-23 14:41
java-home name is OK. 
Here is profiles.clj content:

{:user
  {
  :java-cmd "C:\Program Files\Java\jdk1.7.0_11\bin\java.exe"
  :plugins [
   ]
  }
 }

**Comment by sveri** [comment] 2015-02-23 14:51
Hm, Sorry, but I have no clue. I started a mailing list thread for this: https://groups.google.com/forum/#!topic/clojure/HK03GbbH2Nw with not much input either. Maybe you want to ask there once more for some more input.
I guess somehow you have a setting in your system which overrides something, but like I said, I don't know which one that should be besides the obvious ones which we tried already.

As a workaround you can copy the project from your other PC.

**Comment by enesj** [comment] 2015-02-23 19:43
No problem, I just wanted  to help you to test. I still have one PC to play
with this template.
Thanks

**Comment by sveri** [comment] 2015-02-23 19:46
Ok, so I close this now. If you find the fix / root cause you can reopen it and we will see what to do.
Thanks for helping :-)

**Closed as completed by sveri** 2015-02-23 19:46 UTC
